name: Docker

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  schedule:
    - cron: '38 22 1 * *'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: 0.7.21
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@70fccc794acd729b2b22dd6a326895f286447728
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Put back the git branch into git (Earthly uses it for tagging)
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true
      - name: Earthly Build and Push
        run: earthly --push +all
